name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu klonla
      uses: actions/checkout@v4

    - name: Python kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Buildozer ve gereklilikleri yükle
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libavcodec-dev libavformat-dev libswscale-dev libjpeg-dev libfreetype6-dev
        pip install --upgrade pip setuptools Cython virtualenv
        pip install buildozer

    - name: APK üret
      run: |
        buildozer android debug

    - name: APK dosyasını yükle
      uses: actions/upload-artifact@v4
      with:
        name: sifre_apk.apk
        path: bin/*.apk
