name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v4

      - name: Python'ı kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Buildozer ve bağımlılıkları yükle
        run: |
          sudo apt update
          sudo apt install -y libz-dev libncurses5 libandroid-tools-adb unzip git openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: APK oluştur
        run: |
          buildozer android debug

      - name: APK dosyasını yükle
        uses: actions/upload-artifact@v4
        with:
          name: myapp-release
          path: bin/*.apk
