name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Repo'yu klonla
      uses: actions/checkout@v3

    - name: Python'u kur
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Bağımlılıkları kur
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip git wget
        pip install --upgrade pip
        pip install buildozer cython

    - name: Android SDK Build-Tools 34 kur
      run: |
        yes | sdkmanager --install "build-tools;34.0.0"

    - name: Buildozer'ı hazırla
      run: |
        buildozer android clean

    - name: APK üret
      run: buildozer android debug

    - name: APK'yı yükle
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
